#!/usr/bin/env bash

APP_NAME="http"
SERVER_EXECUTABLE_PATH="./build/example/$APP_NAME/server/$APP_NAME""_server"
SLEEP_SECONDS=1

BUILD_SCRIPT_PATH="./script/build"

WEBBENCH_EXECUTABLE_PATH="./bin/webbench"

if [ $# -gt 2 ]; then
    echo "Usage: $0 [seconds] [repeats]"

    exit 1
fi

number_of_seconds_to_test=${1:-2} # test for 2 seconds each time by default
repeat_times=${2:-5}              # repeat for 5 times total by default

if ! [[ "$number_of_seconds_to_test" =~ ^-?[0-9]+$ ]] || ! [[ "$repeat_times" =~ ^-?[0-9]+$ ]]; then
    echo "Usage: $0 <seconds> <repeat>"

    exit 1
fi

clear

echo "WebBench test time (seconds): $number_of_seconds_to_test"

echo "Building..."

if "$BUILD_SCRIPT_PATH"; then
    echo "Build success ✔️"
else
    echo "Build failed ❌"

    exit 1
fi

echo ""

webbench_max_succeed_number=0

for ((i = 0; i < repeat_times; i++)); do
    echo "--------------------------------"

    echo "Iteration: $((i + 1))"

    "$SERVER_EXECUTABLE_PATH" server-test-"$((i + 1))" &

    pid=$!

    echo "Server started, pid: $pid"

    echo "Sleep for $SLEEP_SECONDS second(s) for the server to be fully initialized..."

    sleep "$SLEEP_SECONDS"

    echo "Resumed"

    echo "Running WebBench..."

    webbench_result="$("$WEBBENCH_EXECUTABLE_PATH" -t "$number_of_seconds_to_test" -c 1000 -2 --get http://127.0.0.1:8080/ 2>&1)"
    webbench_succeed_number="$(echo "$webbench_result" | grep -oP '\d+(?= succeed)')"
    # webbench_min_succeed_number_per_process="$(echo "$webbench_result" | grep -oP '(?<=Min succeed: )\d+')"
    # webbench_max_succeed_number_per_process="$(echo "$webbench_result" | grep -oP '(?<=Max succeed: )\d+')"
    webbench_failed_number="$(echo "$webbench_result" | grep -oP '\d+(?= failed)')"

    echo "WebBench finished, killing server..."

    kill -INT "$pid"

    echo "Sleep for $SLEEP_SECONDS second(s) for the server to be fully shutdown..."

    sleep "$SLEEP_SECONDS"

    echo "Resumed"

    echo "Succeed number: $webbench_succeed_number"
    # echo "Min succeed number: $webbench_min_succeed_number_per_process"
    # echo "Max succeed number: $webbench_max_succeed_number_per_process"
    echo "Failed number: $webbench_failed_number"

    if [ "$webbench_succeed_number" -gt "$webbench_max_succeed_number" ]; then
        webbench_max_succeed_number="$webbench_succeed_number"
    fi
done

average=$((webbench_max_succeed_number / number_of_seconds_to_test))

echo ""

echo "Average: $average"
