#!/usr/bin/env bash

BUILD_DIR=build

clear

# Exit immediately if any command fails
set -e

if ! [ -d "$BUILD_DIR" ]; then
    echo "Creating build directory..."
    mkdir "$BUILD_DIR"
fi

cd "$BUILD_DIR"

echo "Configuring project with CMake..."
cmake ..

echo "Building project..."
make -j"$(nproc)"

echo "Running tests..."
make test
echo "All tests passed. ✔️"
