#!/usr/bin/env bash

BUILD_DIR=build
NEED_TEST=off

# Exit immediately if any command fails
set -e

if ! [ -d "$BUILD_DIR" ]; then
    echo "Creating build directory..."

    mkdir "$BUILD_DIR"
fi

cd "$BUILD_DIR"

echo "Configuring project with CMake..."

cmake .. -DENABLE_TESTING="$NEED_TEST"

echo "Building project..."

make -j"$(nproc)"

if [ "$NEED_TEST" = on ]; then
    echo "Running tests..."

    make test

    echo "All tests are passed. ✔️"

else
    echo "Building completed. ✔️"

fi
