#!/usr/bin/env bash

PROCESS_KEYWORD="run_server"

PID=$(ps aux | grep "$PROCESS_KEYWORD" | grep -v grep | awk '{print $2}')

if [ -n "$PID" ]; then
    kill -9 -"$PID"
fi

PROCESS_KEYWORD="_server"

PID=$(ps aux | grep "$PROCESS_KEYWORD" | grep -v grep | grep -v kill | awk '{print $2}')

if [ -n "$PID" ]; then
    kill -9 "$PID"
fi
