#!/usr/bin/env bash

PERF_EXECUTABLE="/usr/lib/linux-tools-5.15.0-130/perf"

sudo sysctl kernel.perf_event_paranoid=1
sudo sysctl kernel.kptr_restrict=0

"$PERF_EXECUTABLE" script >out.perf

../FlameGraph/stackcollapse-perf.pl out.perf >out.perf.folded

../FlameGraph/flamegraph.pl out.perf.folded >flamegraph.svg

mv -f ./flamegraph.svg example/http/server/static/images/
