#!/usr/bin/env bash

# ./bin/webbench -t 3 -c 10 -2 --get http://127.0.0.1:8080/
# ./bin/webbench -t 3 -c 100 -2 --get http://127.0.0.1:8080/
# ./bin/webbench -t 60 -c 1000 -2 --get http://127.0.0.1:8080/

# ./bin/webbench -t 3 -c 10 -k -2 --get http://127.0.0.1:8080/
# ./bin/webbench -t 3 -c 100 -k -2 --get http://127.0.0.1:8080/
./bin/webbench -t 60 -c 1000 -k -2 --get http://127.0.0.1:8080/

PROCESS_KEYWORD="run_server"

# sends SIGINT to the entire foreground process group, simulating the behaviour of Ctrl+C on the terminal
if [ -n "$PID" ]; then
    kill -INT -"$PID"
fi

PROCESS_KEYWORD="perf_start"

PID=$(ps aux | grep "$PROCESS_KEYWORD" | grep -v grep | awk '{print $2}')

if [ -n "$PID" ]; then
    kill -INT -"$PID"
fi
